language: ruby
rvm:
  - 2.3
node_js:
  - "11"
before_install:
  - npm install -g firebase-tools
install:
  - bundle install
after_install:
  - npm install
script:
- npm run build
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
  token:
    - $FIREBASE_TOKEN
